image: docker:latest

services:
  - docker:dind

stages:
  - release

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - docker info
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -f $CI_COMMIT_TAG/Dockerfile .
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
